Repository dvstechlabs/Noteslify, pull requests merged in 2022-10, with the labels that each got.

#56 Made Single GitIgnore File
  .gitignore
  backend/.gitignore
  frontend/.gitignore
  landing_page/README.md
  landing_page/package-lock.json
  landing_page/package.json
  landing_page/postcss.config.js
  landing_page/public/assets/Vector.png
  landing_page/public/assets/bgimage.png
  landing_page/public/favicon.ico
  landing_page/public/index.html
  landing_page/src/App.js
  landing_page/src/components/About.jsx
  landing_page/src/components/Info.jsx
  landing_page/src/components/Navbar.jsx
  landing_page/src/index.css
  landing_page/src/index.js
  landing_page/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#59 Added Pull Request Template 👨‍💻
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest, hacktoberfest2022

#60 Added Account Page
  README.md
  backend/package-lock.json
  frontend/src/App.js
  frontend/src/components/Account/Account.css
  frontend/src/components/Account/Account.js
  frontend/src/components/Notes/Notes.js
  frontend/src/components/Sidenav/Sidenav.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest2022

#76 Updated Lorem Ipsum Text
  backend/package-lock.json
  frontend/package-lock.json
  frontend/public/assets/mobile2.png
  frontend/public/assets/mobile3.png
  frontend/src/components/Account/Account.js
  frontend/src/components/LandingPage/Components/About/About.js
  frontend/src/components/LandingPage/Components/Contact_form/Contact_form.js
  frontend/src/components/LandingPage/Pages/Contact.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#79 added 404 error page
  frontend/src/App.js
  frontend/src/assets/error404.png
  frontend/src/components/Error/ErrorPage.css
  frontend/src/components/Error/ErrorPage.js
Labels: v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#82 Markdown support to notes
  frontend/package.json
  frontend/src/components/Notes/MarkdownNotes.js
  frontend/src/components/Notes/Notes.css
  frontend/src/components/Notes/Notes.js
  frontend/src/components/Notes/RenderInWindow.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest2022

#86 updated packages
  backend/package-lock.json
  frontend/package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#85 Add ability to search for notes
  backend/db.js
  backend/routes/notes.js
  frontend/package-lock.json
  frontend/src/components/Notes/Notes.js
  frontend/src/components/Sidenav/Sidenav.js
  frontend/src/context/ContextWrapper.js
  frontend/src/context/NotesContext.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#89 menu hover in sidebar is fixed #72
  frontend/package-lock.json
  frontend/src/components/RecycleBin/RecycleBin.css
  frontend/src/components/RecycleBin/RecycleBin.js
  frontend/src/components/Sidenav/Sidenav.css
  frontend/src/components/Sidenav/Sidenav.js
Labels: v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#90 Added SEO Meta Tags on all Pages
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/components/Account/Account.js
  frontend/src/components/Error/ErrorPage.js
  frontend/src/components/ForgotPassword/ForgotPassword.js
  frontend/src/components/Login/Login.js
  frontend/src/components/Notes/Notes.js
  frontend/src/components/RecycleBin/RecycleBin.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#98 image path fixed
  frontend/src/components/LandingPage/Components/Contact_form/Contact.png
  frontend/src/components/LandingPage/Components/Contact_form/Contact_form.js
Labels: bug, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#101 Create FUNDING.yml
  .github/FUNDING.yml
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#123 feat: Added Issue Templates (Form) 🛠
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
  .github/ISSUE_TEMPLATE/OTHER.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: v2.0-roadmap

#130 Error handling for getNotes method - Fix #128
  frontend/src/context/NotesContext.js
Labels: bug, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#153 Added Social Media Icons to Corresponding Links
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/LandingPage/Components/Footer/Footer.js
Labels: documentation, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#155 made contact form working
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/LandingPage/Components/Contact_form/Contact_form.js
Labels: bug, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#150 Copy over styles fixing the layout issues
  frontend/src/components/Notes/RenderInWindow.js
Labels: v2.0-roadmap

#169 fixed dashboard's background height
  frontend/src/App.css
  frontend/src/components/Sidenav/Sidenav.css
Labels: v2.0-roadmap

#174 Removed insecure requests
  frontend/public/index.html
  frontend/src/components/ForgotPassword/ForgotPassword.css
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#175 Made Newsletter Working
  frontend/src/components/LandingPage/Components/Newsletter/NewsLetter.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#149 fixed issue-110 (added encryption of notes)
  backend/helper/helper.js
  backend/models/Notes.js
  backend/routes/notes.js
Labels: v2.0-roadmap

#177 Fixed The Image Background Issue and Some CSS Issues
  frontend/public/assets/mobile.png
  frontend/public/assets/mobile2.png
  frontend/public/assets/mobile3.png
  frontend/src/components/LandingPage/Components/About/About.css
  frontend/src/components/LandingPage/Components/HeroSection/HeroSection.css
Labels: bug, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#180 EDIT & DELETE button's position change
  frontend/src/App.css
  frontend/src/components/Account/Account.css
  frontend/src/components/LandingPage/LandingPage.css
  frontend/src/components/Notes/Notes.css
  frontend/src/components/Notes/Notes.js
Labels: v2.0-roadmap

#184 Added some workflows
  .github/workflows/community.yml
  .github/workflows/labeler.yml
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#191 SignUp/Signin UI modification
  frontend/src/App.css
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#200 Remove labeler
  .github/workflows/labeler.yml
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#202 fixed initial removal of circles
  frontend/src/components/LandingPage/Components/About/About.css
  frontend/src/components/LandingPage/Components/About/About.js
  frontend/src/components/LandingPage/Components/HeroSection/HeroSection.css
  frontend/src/components/LandingPage/Components/HeroSection/HeroSection.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#201 Add Username field length validation
  frontend/src/components/Signup/Signup.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#203 Frontend for Folder Section
  frontend/src/App.js
  frontend/src/components/Folders/Folders.js
  frontend/src/components/Folders/OpenFolder.js
  frontend/src/components/Sidenav/Sidenav.css
  frontend/src/components/Sidenav/Sidenav.js
  frontend/src/data/foldersData.json
  frontend/src/data/notesData.json
  package-lock.json
  package.json
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#204 Added responsive nav bar
  frontend/src/components/LandingPage/Components/NavBar/NavBar.css
  frontend/src/components/LandingPage/Components/NavBar/NavBar.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#205 Removed Commented Code
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/components/LandingPage/Components/Footer/Footer.css
  frontend/src/components/RecycleBin/RecycleBin.css
  frontend/src/components/ResetPassword/ResetPassword.css
Labels: documentation, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#213 Added show and hide password for both Login and SignUp Page
  apps/web/frontend/src/components/Login/Login.js
  apps/web/frontend/src/components/Signup/Signup.js
Labels: enhancement, v2.0-roadmap, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
